sudo: required
dist: trusty
language: node_js
node_js:
  - '10'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - npm i -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - ng build

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
