sudo: required
dist: jammy
language: node_js
node_js:
  - '22.4.0'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm i -g npm@8.19.4
  - npm --version

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm ci

before_script:
  - export NODE_OPTIONS="--max-old-space-size=8192"

script:
  - npm run build-lib
  - npm run build-showcase
  - npm run test

before_deploy:
  - cd dist/systelab-login

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
