sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm install

script:
  - npm run build-lib
  - npm run build-showcase
  - npm run test

before_deploy:
  - cd dist/systelab-login

deploy:
  provider: npm
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
